apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kcl-xencryptionkeys.sijoma.io
spec:
  compositeTypeRef:
    apiVersion: sijoma.io/v1alpha1
    kind: XEncryptionKey
  mode: Pipeline
  pipeline:
  - functionRef:
      name: sijoma-crossplane-functions-by-languagekcl-encryption
    step: kcl-encryption
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
